### ISSUE TITLE
CH1 Requirements

### ISSUE THREAD

**Issue by Bronya-Rand** [team-dds/Switcheroo#3]
To Do:

- [x] Code in Natsuko Route in Script-CH1
- [x] Code in Yuuri Route in Script-CH1
- [x] Code in Satori Route in Script-CH1
- [x] Code in Poem Responses for Natsuko
- [x] Code in Poem Responses for Yuuri
- [x] Code in Poem Responses for Satori
- [x] Code in Poem Responses for Mateo
- [x] Set Up Poem Game

**Comment by Bronya-Rand** [comment]
Refer to PR #2 for Natsuko Route in CH1. Clone decompile-script branch when making the Yuuri or Satori Route or Poem Responses for them + Mateo

**Comment by Gyrosona** [comment]
test

**Comment by Bronya-Rand** [comment]
Satori Route End + Exclusive Coded in. Pending Natsuko Poem Response, Satori Poem Response, Mateo Poem Response and the rest for Yuuri.

**Comment by Bronya-Rand** [comment]
Satori Route Poem Responses coded in. About to push Natsuko and the rest.

**Comment by Bronya-Rand** [comment]
All Poem Responses for Each Broki is now complete with the edited Poem Game. Pending Yuuri Exclusive for push and QA for now.
